version: '3.0'

services:
  axon-server:
    container_name: 'axon-server'
    hostname: axonserver
    image: axoniq/axonserver
    restart: always
    networks:
      - axon-server-network
    environment:
      - "JAVA_TOOL_OPTION=-Xmx512m"
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    volumes:
      - axonserver-data:/data
      - axonserver-eventdata:/eventdata
      - ./axonserver/config:/config

volumes:
  axonserver-data:
    driver: local
  axonserver-eventdata:
    driver: local
  axonserver-config:
    driver: local

networks:
  axon-server-network:
