version: '3.0'

services:
  axon-server:
    container_name: 'axon-server'
    hostname: axonserver
    image: axoniq/axonserver
    restart: always
    networks:
      - axon-server-network
    environment:
      - "JAVA_TOOL_OPTION=-Xmx512m"
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    volumes:
      - axonserver-data:/data
      - axonserver-eventdata:/eventdata
      - axonserver-config:/config

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axonserver/data
      o: bind
  axonserver-eventdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axonserver/eventdata
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axonserver/config
      o: bind

networks:
  axon-server-network: